#! /nix/store/xag5ayq906w9zhlxs8wayv4kvpiyqphq-bash-4.3-p42/bin/bash -e
export UNO_PATH=/nix/store/yzixcdshh56chi4qlqmrndjvdyv2jq0l-libreoffice-5.0.2.2/lib/libreoffice/program/
./.unoconv-wrapped "${extraFlagsArray[@]}" "$@"
